install:
  - mix local.rebar --force; mix local.hex --force; mix deps.get
script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix check && MIX_ENV=test mix coveralls.travis && git -c http.sslBackend=schannel push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.12.1
otp_release: 23.3.1
