name: Autobuild

on:
  repository_dispatch:
    types: run-autodeploy
  schedule:
    - cron: '0 3 5,15,25 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Increment build
      run: N=$(cat BUILD.MD) && echo -n "$((N+1))" > BUILD.MD
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
